"""Logging schema definitions for event field ordering and path fields."""

from __future__ import annotations


DEFAULT_EVENT_KEY_ORDER: list[str] = ["ts", "level", "logger"]


EVENT_KEY_ORDER: dict[str, list[str]] = {
    # Application lifecycle events
    "app_start": [
        "ts",
        "level",
        "assistant_provider",
        "assistant_model",
        "helper_provider",
        "helper_model",
        "profile_file",
        "chat_file",
        "log_file",
        "chats_dir",
        "logs_dir",
        "input_mode",
        "timeout",
        "system_prompt",
    ],
    "app_stop": [
        "ts",
        "level",
        "reason",
        "uptime_ms",
        "error_type",
        "error",
    ],
    "session_start": [
        "ts",
        "level",
        "assistant_provider",
        "assistant_model",
        "helper_provider",
        "helper_model",
        "profile_file",
        "chat_file",
        "log_file",
        "chats_dir",
        "logs_dir",
        "input_mode",
        "timeout",
        "system_prompt",
        "chat_title",
        "chat_summary",
        "message_count",
    ],
    "session_stop": [
        "ts",
        "level",
        "reason",
        "chat_file",
        "message_count",
    ],
    # Command execution events
    "command_exec": [
        "ts",
        "level",
        "command",
        "args_summary",
        "chat_file",
        "elapsed_ms",
    ],
    "command_error": [
        "ts",
        "level",
        "command",
        "args_summary",
        "chat_file",
        "error_type",
        "error",
    ],
    # Chat management events
    "chat_switch": [
        "ts",
        "level",
        "chat_file",
        "trigger",
        "previous_chat_file",
        "message_count",
    ],
    "chat_close": [
        "ts",
        "level",
        "chat_file",
        "message_count",
    ],
    "chat_rename": [
        "ts",
        "level",
        "old_chat_file",
        "new_chat_file",
    ],
    "chat_delete": [
        "ts",
        "level",
        "chat_file",
    ],
    # AI interaction events
    "ai_request": [
        "ts",
        "level",
        "mode",
        "provider",
        "model",
        "chat_file",
        "message_count",
        "input_chars",
        "has_system_prompt",
    ],
    "ai_response": [
        "ts",
        "level",
        "mode",
        "provider",
        "model",
        "chat_file",
        "latency_ms",
        "ttft_ms",
        "output_chars",
        "input_tokens",
        "cached_tokens",
        "cache_write_tokens",
        "output_tokens",
        "total_tokens",
        "estimated_cost",
    ],
    "ai_error": [
        "ts",
        "level",
        "mode",
        "provider",
        "model",
        "chat_file",
        "latency_ms",
        "http_method",
        "http_url",
        "http_version",
        "http_status",
        "http_reason",
        "error_type",
        "error",
    ],
    # Helper AI events
    "helper_ai_request": [
        "ts",
        "level",
        "task",
        "provider",
        "model",
        "message_count",
        "input_chars",
        "has_system_prompt",
    ],
    "helper_ai_response": [
        "ts",
        "level",
        "task",
        "provider",
        "model",
        "latency_ms",
        "ttft_ms",
        "output_chars",
        "input_tokens",
        "cached_tokens",
        "cache_write_tokens",
        "output_tokens",
        "total_tokens",
        "estimated_cost",
    ],
    "helper_ai_error": [
        "ts",
        "level",
        "task",
        "provider",
        "model",
        "latency_ms",
        "http_method",
        "http_url",
        "http_version",
        "http_status",
        "http_reason",
        "error_type",
        "error",
    ],
    # Provider validation events
    "provider_validation_error": [
        "ts",
        "level",
        "provider",
        "model",
        "phase",
        "chat_file",
        "http_method",
        "http_url",
        "http_version",
        "http_status",
        "http_reason",
        "error_type",
        "error",
    ],
    "provider_log": [
        "ts",
        "level",
        "provider",
        "message",
    ],
    "provider_retry": [
        "ts",
        "level",
        "provider",
        "operation",
        "attempt",
        "sleep_sec",
        "result",
        "error_type",
        "error",
        "function",
    ],
    "httpx_request": [
        "ts",
        "level",
        "logger",
        "http_method",
        "http_url",
        "http_version",
        "http_status",
        "http_reason",
    ],
}


LOG_PATH_FIELDS: set[str] = {
    "profile_file",
    "chat_file",
    "log_file",
    "chats_dir",
    "logs_dir",
    "previous_chat_file",
    "old_chat_file",
    "new_chat_file",
    "system_prompt",
    # Backward compatibility if an older call site still emits this key.
    "system_prompt_path",
}
